name: Build
on:
  push:
    branches:
      - master

jobs:
  build:

    # using Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '12.x'
          
    - run: npm install
    - run: ng build --prod
